// <auto-generated />
using System;
using CombineSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CombineSample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230503131536_yourmigrations4")]
    partial class yourmigrations4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombineSample.Models.AddEmployee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("employeeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeId");

                    b.ToTable("AddEmployee_Details");
                });

            modelBuilder.Entity("CombineSample.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("employeeLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("employee_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("employee_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_technology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_end_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_start_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_working_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employmentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.ToTable("Employee_Details");
                });

            modelBuilder.Entity("CombineSample.Models.Manager", b =>
                {
                    b.Property<int>("manager_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("manager_id"));

                    b.Property<byte[]>("manager_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("manager_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("manager_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("manager_id");

                    b.ToTable("Manager_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
