// <auto-generated />
using CombineSample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CombineSample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230427120547_yourMigration1")]
    partial class yourMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CombineSample.Models.Employee", b =>
                {
                    b.Property<int>("employee_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employee_id"));

                    b.Property<byte[]>("employee_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("employee_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_technology")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_end_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_req")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_vacation_start_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_working_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.ToTable("Employee_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
